// ═══════════════════════════════════════════════════════════════
//  SportVerge — AISummary
//  ─────────────────────────────────────────────────────────────
//  🤖 AI-ის მიერ გენერირებული შეჯამება მატჩის/სიახლის შესახებ
//
//  📍 გამოიყენება:
//     - მატჩის დეტალურ გვერდზე
//     - "Two Sides" სექციაში
//     - სიახლეების დეტალებში
//     - Predictions hub-ზე
//
//  ✨ Features:
//     - Streaming/typewriter effect (optional)
//     - Copy to clipboard
//     - Regenerate callback
//     - Key points list
//     - Confidence indicator
//     - Provider badge (gemini/heuristic)
//     - Trend indicator
//     - Skeleton loading state
//     - Multi-language support
//     - Fully responsive
// ═══════════════════════════════════════════════════════════════

"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Sparkles,
  TrendingUp,
  TrendingDown,
  Minus,
  Copy,
  Check,
  RefreshCw,
  Loader2,
  Quote,
  Zap,
  Brain,
} from "lucide-react";

// ─────────────────────────────────────────────────────────────
//  📐 TYPES
// ─────────────────────────────────────────────────────────────

type Locale = "ka" | "en" | "ru";
type Trend = "up" | "down" | "neutral";
type Confidence = "low" | "medium" | "high";
type Provider = "gemini" | "heuristic" | "pollinations";

export interface AISummaryProps {
  /** შეჯამების ტექსტი */
  text: string;
  /** სათაური (default: "AI Summary") */
  title?: string;
  /** ტენდენცია */
  trend?: Trend;
  /** მთავარი დასკვნები (bullet points) */
  keyPoints?: string[];
  /** ნდობის დონე */
  confidence?: Confidence;
  /** წყარო (gemini, heuristic, ...) */
  provider?: Provider;
  /** სპორტის ტიპი (icon-ისთვის) */
  sport?: "football" | "basketball" | "tennis" | "f1" | "ufc" | "other";
  /** ენა */
  locale?: Locale;
  /** დამატებითი კლასები */
  className?: string;
  /** ანიმაციის ჩართვა */
  animated?: boolean;
  /** Streaming (typewriter) ეფექტი */
  streaming?: boolean;
  /** Copy ღილაკის ჩვენება */
  showCopy?: boolean;
  /** Regenerate callback */
  onRegenerate?: () => void | Promise<void>;
  /** Loading state (თუ AI პასუხს ელოდება) */
  loading?: boolean;
}

// ─────────────────────────────────────────────────────────────
//  🌍 TRANSLATIONS
// ─────────────────────────────────────────────────────────────

interface Translations {
  summary: string;
  keyPoints: string;
  copy: string;
  copied: string;
  regenerate: string;
  generatedBy: string;
  confidence: string;
  low: string;
  medium: string;
  high: string;
  thinking: string;
}

function getT(locale: Locale): Translations {
  if (locale === "ka") {
    return {
      summary: "AI შეჯამება",
      keyPoints: "მთავარი დასკვნები",
      copy: "კოპირება",
      copied: "დაკოპირდა!",
      regenerate: "თავიდან გენერაცია",
      generatedBy: "გენერირებულია AI-ით",
      confidence: "ნდობა",
      low: "დაბალი",
      medium: "საშუალო",
      high: "მაღალი",
      thinking: "ვაანალიზებ...",
    };
  }
  if (locale === "ru") {
    return {
      summary: "AI резюме",
      keyPoints: "Ключевые выводы",
      copy: "Копировать",
      copied: "Скопировано!",
      regenerate: "Перегенерировать",
      generatedBy: "Сгенерировано AI",
      confidence: "Уверенность",
      low: "Низкая",
      medium: "Средняя",
      high: "Высокая",
      thinking: "Анализирую...",
    };
  }
  return {
    summary: "AI Summary",
    keyPoints: "Key Takeaways",
    copy: "Copy",
    copied: "Copied!",
    regenerate: "Regenerate",
    generatedBy: "Generated by AI",
    confidence: "Confidence",
    low: "Low",
    medium: "Medium",
    high: "High",
    thinking: "Analyzing...",
  };
}

// ─────────────────────────────────────────────────────────────
//  🎨 CONFIG
//  ─────────────────────────────────────────────────────────────

const TREND_CONFIG: Record<
  Trend,
  { icon: typeof TrendingUp; color: string; bg: string; border: string; label: Record<Locale, string> }
> = {
  up: {
    icon: TrendingUp,
    color: "text-success",
    bg: "bg-success/10",
    border: "border-success/30",
    label: { ka: "მზარდი", en: "Rising", ru: "Растущий" },
  },
  down: {
    icon: TrendingDown,
    color: "text-danger",
    bg: "bg-danger/10",
    border: "border-danger/30",
    label: { ka: "კლებადი", en: "Falling", ru: "Падающий" },
  },
  neutral: {
    icon: Minus,
    color: "text-muted",
    bg: "bg-muted/10",
    border: "border-muted/30",
    label: { ka: "ნეიტრალური", en: "Neutral", ru: "Нейтральный" },
  },
};

const CONFIDENCE_CONFIG: Record<
  Confidence,
  { color: string; bg: string; border: string; width: string }
> = {
  low: {
    color: "text-amber-400",
    bg: "bg-amber-500/10",
    border: "border-amber-500/30",
    width: "w-1/3",
  },
  medium: {
    color: "text-teal-400",
    bg: "bg-teal-500/10",
    border: "border-teal-500/30",
    width: "w-2/3",
  },
  high: {
    color: "text-lime-400",
    bg: "bg-lime-500/10",
    border: "border-lime-500/30",
    width: "w-full",
  },
};

const PROVIDER_LABELS: Record<Provider, { emoji: string; name: string }> = {
  gemini: { emoji: "✨", name: "Gemini" },
  heuristic: { emoji: "📊", name: "Heuristic" },
  pollinations: { emoji: "🌸", name: "Pollinations" },
};

// ─────────────────────────────────────────────────────────────
//  🎬 STREAMING TEXT HOOK
// ─────────────────────────────────────────────────────────────

function useStreamingText(text: string, enabled: boolean) {
  const [displayed, setDisplayed] = useState(enabled ? "" : text);
  const [isDone, setIsDone] = useState(!enabled);

  useEffect(() => {
    if (!enabled) {
      setDisplayed(text);
      setIsDone(true);
      return;
    }

    setDisplayed("");
    setIsDone(false);

    const chars = Array.from(text);
    const speedMs = Math.max(8, Math.min(25, 1500 / chars.length));
    let idx = 0;
    let cancelled = false;

    const timer = setInterval(() => {
      if (cancelled) return;
      idx += 1;
      setDisplayed(chars.slice(0, idx).join(""));
      if (idx >= chars.length) {
        clearInterval(timer);
        setIsDone(true);
      }
    }, speedMs);

    return () => {
      cancelled = true;
      clearInterval(timer);
    };
  }, [text, enabled]);

  return { displayed, isDone };
}

// ─────────────────────────────────────────────────────────────
//  🎯 MAIN COMPONENT
// ─────────────────────────────────────────────────────────────

export function AISummary({
  text,
  title,
  trend = "neutral",
  keyPoints = [],
  confidence,
  provider,
  sport,
  locale = "ka",
  className = "",
  animated = true,
  streaming = false,
  showCopy = true,
  onRegenerate,
  loading = false,
}: AISummaryProps) {
  const t = getT(locale);
  const trendCfg = TREND_CONFIG[trend];
  const TrendIcon = trendCfg.icon;

  const [copied, setCopied] = useState(false);
  const [regenerating, setRegenerating] = useState(false);

  const { displayed, isDone } = useStreamingText(text, streaming);

  // ─── Copy handler ───
  async function handleCopy() {
    try {
      const copyText =
        keyPoints.length > 0
          ? `${text}\n\n${t.keyPoints}:\n${keyPoints.map((p) => `• ${p}`).join("\n")}`
          : text;

      await navigator.clipboard.writeText(copyText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Silent fail
    }
  }

  // ─── Regenerate handler ───
  async function handleRegenerate() {
    if (!onRegenerate || regenerating) return;
    setRegenerating(true);
    try {
      await onRegenerate();
    } finally {
      setRegenerating(false);
    }
  }

  // ═══ LOADING STATE ═══
  if (loading) {
    return (
      <div
        className={`w-full bg-gradient-to-br from-surface/80 to-surface/40 backdrop-blur-xl border border-edge rounded-2xl p-5 lg:p-6 ${className}`}
      >
        <div className="flex items-center gap-2 mb-4">
          <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-lime to-teal flex items-center justify-center">
            <Brain size={14} className="text-ink animate-pulse" />
          </div>
          <span className="text-xs lg:text-sm font-semibold text-text uppercase tracking-wider">
            {title ?? t.summary}
          </span>
        </div>

        <div className="flex items-center gap-3 text-muted">
          <Loader2 size={16} className="animate-spin text-lime" />
          <span className="text-sm">{t.thinking}</span>
        </div>

        <div className="mt-4 space-y-2">
          <div className="h-3 bg-surface/60 rounded animate-pulse" />
          <div className="h-3 bg-surface/60 rounded animate-pulse w-5/6" />
          <div className="h-3 bg-surface/60 rounded animate-pulse w-4/6" />
        </div>
      </div>
    );
  }

  // ═══ MAIN ═══
  return (
    <motion.div
      initial={animated ? { opacity: 0, y: 12 } : false}
      animate={animated ? { opacity: 1, y: 0 } : false}
      transition={{ duration: 0.5 }}
      className={`group relative w-full bg-gradient-to-br from-surface/80 to-surface/40 backdrop-blur-xl border border-edge rounded-2xl p-5 lg:p-6 overflow-hidden ${className}`}
    >
      {/* ═══ Ambient glows ═══ */}
      <div className="absolute -top-20 -left-20 w-40 h-40 bg-lime/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute -bottom-20 -right-20 w-40 h-40 bg-teal/10 rounded-full blur-3xl pointer-events-none" />

      {/* ═══ Top gradient line ═══ */}
      <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-lime/60 to-transparent" />

      {/* ═══ HEADER ═══ */}
      <header className="relative flex items-center justify-between gap-3 mb-4 flex-wrap">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-lime to-teal flex items-center justify-center shadow-[0_0_15px_rgba(217,249,157,0.4)]">
            <Sparkles size={14} className="text-ink" />
          </div>
          <span className="text-xs lg:text-sm font-semibold text-text uppercase tracking-wider">
            {title ?? t.summary}
          </span>
          {sport && (
            <span className="text-base leading-none" aria-hidden="true">
              {
                {
                  football: "⚽",
                  basketball: "🏀",
                  tennis: "🎾",
                  f1: "🏎️",
                  ufc: "🥊",
                  other: "🎯",
                }[sport]
              }
            </span>
          )}
        </div>

        <div className="flex items-center gap-2">
          {/* Trend badge */}
          <div
            className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full ${trendCfg.bg} border ${trendCfg.border}`}
          >
            <TrendIcon size={12} className={trendCfg.color} />
            <span className={`text-[10px] lg:text-xs font-medium ${trendCfg.color}`}>
              {trendCfg.label[locale]}
            </span>
          </div>
        </div>
      </header>

      {/* ═══ TEXT ═══ */}
      <div className="relative">
        <Quote
          size={28}
          className="absolute -top-2 -left-1 text-lime/15 select-none"
          aria-hidden="true"
        />

        <p className="relative text-sm lg:text-base text-text/90 leading-relaxed pl-5 whitespace-pre-wrap">
          {displayed}
          {streaming && !isDone && (
            <motion.span
              animate={{ opacity: [1, 0] }}
              transition={{ duration: 0.5, repeat: Infinity }}
              className="inline-block w-2 h-4 bg-lime ml-0.5 align-middle"
            />
          )}
        </p>
      </div>

      {/* ═══ KEY POINTS ═══ */}
      {keyPoints.length > 0 && (
        <motion.div
          initial={animated ? { opacity: 0, y: 8 } : false}
          animate={animated ? { opacity: 1, y: 0 } : false}
          transition={{ duration: 0.4, delay: 0.2 }}
          className="relative mt-5 pt-4 border-t border-edge/50"
        >
          <div className="flex items-center gap-1.5 mb-3">
            <Zap size={12} className="text-lime" />
            <span className="text-[10px] uppercase tracking-widest text-lime font-bold">
              {t.keyPoints}
            </span>
          </div>
          <ul className="space-y-2">
            {keyPoints.map((point, i) => (
              <motion.li
                key={i}
                initial={animated ? { opacity: 0, x: -8 } : false}
                animate={animated ? { opacity: 1, x: 0 } : false}
                transition={{ duration: 0.3, delay: 0.05 * i + 0.3 }}
                className="flex items-start gap-2.5 text-sm text-text/85"
              >
                <span className="shrink-0 mt-1.5 w-1.5 h-1.5 rounded-full bg-lime/60" />
                <span className="leading-relaxed">{point}</span>
              </motion.li>
            ))}
          </ul>
        </motion.div>
      )}

      {/* ═══ CONFIDENCE BAR ═══ */}
      {confidence && (
        <div className="relative mt-4 pt-4 border-t border-edge/50">
          <div className="flex items-center justify-between mb-2">
            <span className="text-[10px] uppercase tracking-widest text-muted">
              {t.confidence}
            </span>
            <span
              className={`text-[10px] font-bold uppercase tracking-wider ${CONFIDENCE_CONFIG[confidence].color}`}
            >
              {t[confidence]}
            </span>
          </div>
          <div className="h-1.5 bg-surface/60 rounded-full overflow-hidden">
            <motion.div
              initial={animated ? { width: 0 } : { width: "100%" }}
              animate={{ width: "100%" }}
              transition={{ duration: 0.8, delay: 0.3, ease: "easeOut" }}
              className={`h-full rounded-full bg-gradient-to-r from-lime to-teal ${CONFIDENCE_CONFIG[confidence].width}`}
              style={{ width: CONFIDENCE_CONFIG[confidence].width }}
            />
          </div>
        </div>
      )}

      {/* ═══ FOOTER ═══ */}
      <footer className="relative mt-5 pt-4 border-t border-edge/50 flex items-center justify-between gap-3 flex-wrap">
        {/* Left — provider + status */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1.5">
            <span className="w-1.5 h-1.5 rounded-full bg-teal animate-pulse" />
            <span className="text-[10px] text-muted">{t.generatedBy}</span>
          </div>
          {provider && (
            <span className="inline-flex items-center gap-1 text-[10px] px-2 py-0.5 rounded-full bg-surface/60 border border-edge text-muted">
              <span>{PROVIDER_LABELS[provider].emoji}</span>
              <span>{PROVIDER_LABELS[provider].name}</span>
            </span>
          )}
        </div>

        {/* Right — actions */}
        <div className="flex items-center gap-1.5">
          {showCopy && (
            <button
              onClick={handleCopy}
              disabled={!isDone}
              className="group/btn inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-surface/60 hover:bg-surface border border-edge hover:border-lime/40 text-[10px] font-medium text-muted hover:text-lime transition-all disabled:opacity-40 disabled:cursor-not-allowed"
              aria-label={t.copy}
              title={t.copy}
            >
              <AnimatePresence mode="wait" initial={false}>
                {copied ? (
                  <motion.span
                    key="check"
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    exit={{ scale: 0 }}
                    className="flex items-center gap-1.5"
                  >
                    <Check size={11} className="text-lime" />
                    <span className="text-lime">{t.copied}</span>
                  </motion.span>
                ) : (
                  <motion.span
                    key="copy"
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    exit={{ scale: 0 }}
                    className="flex items-center gap-1.5"
                  >
                    <Copy size={11} />
                    <span>{t.copy}</span>
                  </motion.span>
                )}
              </AnimatePresence>
            </button>
          )}

          {onRegenerate && (
            <button
              onClick={handleRegenerate}
              disabled={regenerating || loading}
              className="inline-flex items-center justify-center w-7 h-7 rounded-lg bg-surface/60 hover:bg-surface border border-edge hover:border-teal/40 text-muted hover:text-teal transition-all disabled:opacity-40 disabled:cursor-not-allowed"
              aria-label={t.regenerate}
              title={t.regenerate}
            >
              <RefreshCw
                size={12}
                className={regenerating ? "animate-spin" : ""}
              />
            </button>
          )}
        </div>
      </footer>
    </motion.div>
  );
}

export default AISummary;